image: Visual Studio 2017

platform: x64

configuration: Release

init:
  - git config --global core.autocrlf input

branches:
  only:
  - master

clone_folder: c:\work\kurwa
shallow_clone: true

matrix:
  fast_finish: true

before_build:
  - cmd: git lfs pull
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 15 2017 Win64" ..

build:
  project: build\all.sln
  parallel: true
  verbosity: normal

test_script:
  - cmd: cd bin/Release
  - cmd: unittest.exe
