image: Visual Studio 2017

platform: x64

configuration: Release

init:
  - git config --global core.autocrlf input

clone_folder: c:\work\kurwa
shallow_clone: true

matrix:
  fast_finish: false

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 15 2017 Win64" ..

build:
  project: build\all.sln
  parallel: true
  verbosity: normal

after_build:
  - cmd: cd bin/Release
  - cmd: dir
  - cmd: unittest.exe
