image: Visual Studio 2017

platform: x64

configuration: Release

branches:
  only:
  - master

clone_folder: c:\work\kurwa

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 15 2017 Win64" ..

build:
  project: build\all.sln
  parallel: true
  verbosity: normal

test_script:
  - cmd: cd bin/Release
  - cmd: unittest.exe
