dist: trusty
sudo: false

language: c++

branches:
  only:
    - master

jobs:
  include:
    - name: 'Linux: Codeformat'
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_script:
        - sudo apt-get install clang-format-6.0
        - sudo ln -sf /usr/bin/clang-format-6.0 /usr/bin/clang-format
      script:
        - python script/codeformat/check_style.py
    - name: 'Linux: Build & unittest'
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_script:
        - export CC=clang-6.0
        - export CXX=clang++-6.0
      script:
        - git lfs pull
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . -- -j 2
        - cd bin
        - ./unittest
    - name: "MacOS: Build & Unittest"
      os: osx
      osx_image: xcode9.4
      before_script:
        - brew install git-lfs
        - git lfs install
      script:
        - git lfs pull
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . -- -j 2
        - cd bin
        - ./unittest.app/Contents/MacOS/unittest
