dist: trusty
sudo: required

language: cpp

os: linux

before_install:
    - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main"
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq clang++-6.0
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0

before_script:
    - mkdir build
    - cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build .

after_script:
    - ls
    - ls -a