dist: trusty
sudo: false

language: c++

branches:
  only:
    - master

jobs:
  include:
    - stage: 'codeformat'
      os: linux
      script:
        - python script/codeformat/check_style.py
    - stage: 'build & unittest'
      script:
        - git lfs pull
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . -- -j 2
        - cd bin
        - if [ `uname` = 'Darwin' ]; then
          ./unittest.app/Contents/MacOS/unittest;
          else
          ./unittest;
          fi

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_script:
        - export CC=clang-6.0
        - export CXX=clang++-6.0
    - os: osx
      osx_image: xcode9.4
      before_script:
        - brew install git-lfs
        - git lfs install
