dist: trusty
sudo: required

language: c++

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build .
    - ls
    - ls -a

matrix:
  include:
    - os: linux
      compiler: clang-6.0
      env:
        - C_COMPILER=clang-6.0
        - CXX_COMPILER=clang++-6.0
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    - os: osx
      osx_image: xcode9.3
      env:
        - C_COMPILER=clang
        - CXX_COMPILER=clang++
