dist: trusty
sudo: false

language: c++

branches:
  only:
    - master

jobs:
  include:
    - name: 'Linux: Code Format & Build & Unittest'
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-6.0
            - clang-format-6.0
            - libdbus-1-dev
            - libibus-1.0-dev
            - fcitx-libs-dev
            - libxss-dev
          sources:
            - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_script:
        - export CC=clang-6.0
        - export CXX=clang++-6.0
        - sudo ln -sf /usr/bin/clang-format-6.0 /usr/bin/clang-format
        - git submodule update --init --recursive
      script:
        - python script/codeformat/check_style.py
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . -- -j 2
        - cd bin
        - ./unittest
    - name: "MacOS: Build & Unittest"
      os: osx
      osx_image: xcode9.4
      before_script:
        - git submodule update --init --recursive
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build . -- -j 2
        - cd bin
        - ./unittest
