dist: trusty
sudo: required

language: c++

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - bin/unittest

matrix:
  include:
    - os: linux
      compiler: clang-6.0
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_script:
          - export CC=clang-6.0
          - export CXX=clang++-6.0
    - os: osx
      osx_image: xcode9.4
